### ISSUE TITLE
Warning: class OBJECT_OT_sym contains a properties which should be an annotation!

### ISSUE THREAD

**Issue by javitang** [jayanam/fast-carve#10]
Hi.
My English is terrible so I use the google translator. I apologize beforehand.
In the file fc_utils_op.py on line 41 you have to replace the sign of "=" with ":" so that the warning (Warning: class OBJECT_OT_sym contains a properties which should be annotation!) Does not appear when starting blender. I suppose that this comment already you will know it but good here I leave it so that it does not forget to modify it.
Here a link https://wiki.blender.org/wiki/Reference/Release_Notes/2.80/Python_API/Addons
Great work that has been done with your addon.
regards

**Comment by jayanam** [comment]
Yes I know, but thx:-)
