### ISSUE TITLE
Suggested feature: Move the Primitive by a specific step (or create array of the primitive)

### ISSUE THREAD

**Issue by raindropsfromsky** [jayanam/fast-carve#16]
The "slice" video at your YouTube **channel** ([link](https://www.youtube.com/watch?v=Con5uMDwRQ0)) shows how to move the primitive and repeat the **Slice** operation. This creates a shape like a engine box with fins.

However, there are some issues:'
1. The primitive cannot be shifted by the same precise amount each time. This creates fins with uneven thickness.

2. We cannot know in advance how many primitives can be fitted in the available width. The last fin is very likely to be different compared to the other fins.

There are a few alternative solutions:
1. Add control to shift the primitive by a precise amount. The gape can be defined in terms of the primitive's own dimension in that particular direction. Or it can be in terms of absolute units (mm, cm, inch, m, foot, etc)

2. Let the user define the total length in which he has to fit x primitive shapes, while leaving equal gaps between the instances. For example, the primitive is 3 mm wide, and the user wants to specify 5 such primitives in a 25 mm length. This means the 5 primitives will occupy a width of 15 mm, and the rest 10 mm gap will have to be equally distributed between the 5 instances.

3. Create an array of primitives, with number of instances and gap defines. The user can check out the effect and adjust the array's parameters before applying the settings.

**Comment by jayanam** [comment]
This can be adressed by using the new array features.
