### ISSUE TITLE
High DPI displays options

### ISSUE THREAD

**Issue by thmrtnz** [jayanam/fast-carve#21]
Hello.

Fantastic addon, thank you very much. 

I have a suggestion for improvement to the UI. Could the user somehow adjust the size of the panel in 3DVIEW? It does not scale well with Retina displays, on macOS.

![screen shot 2019-02-17 at 13 10 51](https://user-images.githubusercontent.com/47714003/52912774-7d5a0900-32b6-11e9-88c1-28ef575872fd.jpg)

**Comment by jayanam** [comment]
The sze of the panels can be adjusted by dragging with the mouse (left right), you can collapse the panels by clicking the header and you can also set the size by clicking the middle mouse button, pressing the ctrl key and then moving the mouse over the panel.
