### ISSUE TITLE
Bevel-Object: Error (Line 32, 47) "..."no attribute 'edge_weight_method'.."

### ISSUE THREAD

**Issue by BastoBullfrogW** [jayanam/fast-carve#25]
Bevel Object seems to doesnt work.

Used Blender Build: 
Date: 2019-03-01 
Hash: e795dd4a20a1

Used Fast Carve Build:
0.9.7

![image](https://user-images.githubusercontent.com/48360779/54040403-8f4c0f00-41c5-11e9-9a55-7576aa660ad5.png)

**Comment by BastoBullfrogW** [comment]
I will try the newest Blender Build as well and give some feedback soon as possible

**Comment by jayanam** [comment]
It's fixed, but be sure to remove the old version, close Blender, then
install the new one
