### ISSUE TITLE
Installing fast carve causes various issues 

### ISSUE THREAD

**Issue by andyp60** [jayanam/fast-carve#27]
I've installed fast carve  into 64 bit blender 2.80 and it immediately causes several issues. First off it does appear in the addons list
![install from add on](https://user-images.githubusercontent.com/11356689/54094498-fb19ad80-4366-11e9-9066-f8628a3f46ac.jpg)

The only way to clear is by deleting the following C:\Users\<user>\AppData\Roaming\Blender Foundation\Blender\2.80\scripts

![2019-03-10 18_55_23-Greenshot](https://user-images.githubusercontent.com/11356689/54094404-39629d00-4366-11e9-9ea8-55de0824b563.jpg)

![2019-03-10 18_23_08-Blender Preferences](https://user-images.githubusercontent.com/11356689/54094219-ed632880-4364-11e9-919e-b5477dd6ea92.jpg)
![2019-03-10 18_10_24- save system info error](https://user-images.githubusercontent.com/11356689/54094220-ed632880-4364-11e9-933a-da33c35ee2cd.png)
![2019-03-10 18_08_28-Blender splash](https://user-images.githubusercontent.com/11356689/54094221-ed632880-4364-11e9-96e3-c6caa6584418.jpg)
[system-info.txt](https://github.com/jayanam/fast-carve/files/2950250/system-info.txt)
![2019-03-10 18_25_24-Blender internal error](https://user-images.githubusercontent.com/11356689/54094222-edfbbf00-4364-11e9-8b31-1978c2383eff.png)

**Comment by jayanam** [comment]
The exception you are posting here dont seem to have anything to do with
Fast Carve. Perhaps your Blender is corruped. I also cant reproduce this. I
recommend re-installing the latest Blender version.

**Comment by jayanam** [comment]
And the installation path for fast carve (and other addons) should be:

C:\Users\your_username}AppData\Roaming\Blender
Foundation\Blender\2.80\scripts\addons\fast-carve-fast-carve-2-8

when you just install from script

**Comment by jayanam** [comment]
Here is how to install Fast Carve and addons in Blender:
https://youtu.be/14G_YIVdBd0
