### ISSUE TITLE
I cannot operate any Boolean with primitives

### ISSUE THREAD

**Issue by raindropsfromsky** [jayanam/fast-carve#30]
I created a polyline Primitive, and extruded it. 
IINW the Primitive section must be in **Create** mode, so that I can create an object from the Primitive.

But at this stage, I cannot do any Boolean operation between this extruded object and target.
All the four Boolean operation buttons are disabled at the top of the GUI.

![image](https://user-images.githubusercontent.com/9047168/54576322-9ffa5180-4a1d-11e9-949b-c5cb98512316.png)

What am I doing wrong?

There is a second confusion also: The check box says "Apply immediately". But when all four Boolean operation buttons are disabled, what will be applied? 

And exactly when will it be applied? When I finish the extrusion of the primitive?

A third problem is that when the "apply immediately" checkbox is enabled, the **Apply Boolean** button should not remain active (because both of them cannot be active simultaneously).

A fourth confusion is that the the four Boolean buttons at the top of the GUI and the drop-down list in Primitive section seem to do the same thing (operate Boolean operation between two objects). Why are there two separate controls? What's the difference in how they operate?

On the whole, the GUI should be revamped, IMHO.

**Comment by jayanam** [comment]
You need to select the new object that is created and you have to define
the target. Then the buttons will be enabled.

**Comment by raindropsfromsky** [comment]
Ok, as soon as I selected the extruded object, the four buttons at the top got activated.

But I still have the following issues:
1. When the "apply immediately" checkbox is enabled, the **Apply Booleans** button should be disabled. But it is not disabled.

2. I tried to delete all objects of my experiment. I could delete everything, except the original extruded polyline (which appears as a blue wireframed object). Finally I pressed ESC and it vanished. This is not intuitive.

**Comment by jayanam** [comment]
Ok, but please open a separate issue for this, cause it has nothing to to with the original issue, which I will close now.

Point 1. : Ok, sounds legit
Point 2. : Deleting the objects is not the same as deleting the primitive - and the primitive should stay active til you close the primitive mode cause it can be reused.
