### ISSUE TITLE
The **Selected as target** button should be moved to the top (or better, eliminated)

### ISSUE THREAD

**Issue by raindropsfromsky** [jayanam/fast-carve#41]
The **Booleans** section of the GUI has two separate controls to select the target:
1. The **Target** drop-down list, at the top of the section
2. The **Selected as target** button, at the bottom of the section 

![image](https://user-images.githubusercontent.com/9047168/62670568-4afdae80-b9b1-11e9-99d6-487352f530d6.png)

Logically, they should be placed next to each other, because they do the same function.

In fact, the "selected as target" is really one of the options in the **Target** drop-down list.
Thus it does not deserve to be an independent control.

**Desired:** 
At minimum, move the **Selected as target** button just below the **Target** drop-down list.

But ideally, this button should not be separate at all: It should be the top option (named "Selected object") in the drop-down list. Provide a separator line below it, and then provide the list of all objects in the scene.

**Comment by jayanam** [comment]
Moved the selected as target bewlow the target and is also available in sculpt mode now
