### ISSUE TITLE
Bug: The addon has duplicate Boolean modes under "Boolean" and "Primitive" sections

### ISSUE THREAD

**Issue by raindropsfromsky** [jayanam/fast-carve#45]
The addon seems to have duplicate Boolean modes under "Boolean" and "Primitive" sections, as shown below:

**1. In the Boolean section:**
![image](https://user-images.githubusercontent.com/9047168/62825612-7dcfbe80-bbcc-11e9-95b6-8dbb49dd331e.png)

**2. In the Primitive section:**
![image](https://user-images.githubusercontent.com/9047168/62825620-a22b9b00-bbcc-11e9-9c37-0e30292bbed0.png)

This duplication creates unnecessary complications.

The Boolean operations should be limited to the **Boolean** section. The Primitive section should only control the creation of the primitive and extrusion. When the Primitive is extruded, a new object is created. Now the **Boolean** section of the Addon can be used on it. So the Boolean controls are not at all needed in the **Primitive** section.

**Comment by jayanam** [comment]
No, because then you have one redundant step if you want for example create a difference operation.

**Comment by raindropsfromsky** [comment]
That is the point: Why should we have a redundant step when the same controls are already provided in the top section? 

If the Booleans for Primitives and Booleans for solid shapes work differently, then it is justifiable.
But here they work identically.
 
Removing duplication makes the GUI much cleaner.

**Comment by jayanam** [comment]
No these are totally different tools. The mode for primitives (which really could be renamed to boolean type) is applied automatically after creating a primitive. This is why you dont have to create a new primitive and then click again to do a boolean operation. The Booleans are explicit operations that you do when not in primitive mode.

**Comment by raindropsfromsky** [comment]
Even if the control is renamed as **Boolean**, the same point remains: The **Primitive** section does not need a Boolean mode at all.

There are two main reasons:
1. The **Boolean** section can work with objects that are NOT created by the FastCarve addon. On the other hand, the **Primitives** section can create new objects that are not used for any **Boolean** operations. Thus both sections are functionally independent.
2. For the **Boolean** section, any objects created by the **Primitives** section are like any other objects in the Editor: They are not special in any way. (For example, there is no internal pipeline to pass all objects created by the **Primitives** section to the **Boolean** section.)

That's why the **Primitives** section should not have any Boolean function. Then the addon becomes truly modular.

Once the user is aware that there are three independent modules in this addon, he can adroitly use all three modules independently, with objects created and modified _outside_ the addon.

That's why if the Boolean functionality is duplicated in the **Primitive** section, it will dilute the modular nature of the **Boolean** section.

Sorry for the long post. I hope I have convinced you.
