### ISSUE TITLE
not installing/ enabling in blender 2.80.39

### ISSUE THREAD

**Issue by mak-bd** [jayanam/fast-carve#6]

**Comment by mak-bd** [comment]
issue closed, after restarting blender, it is enabled correctly.

**Comment by sommerper** [comment]
I just tried installing and I'm told it needs to be upgraded to 2.80. Restarting didn't work.

**Comment by jayanam** [comment]
Did you install from zip?

**Comment by sommerper** [comment]
You beat me to it. I goggled fast carve 2.8 and it led me to that repo. Sorry about that and thanks for the reply.
